/** =====================
 * post-load functions
===================== **/var viewportWidth=Math.max(document.documentElement.clientWidth,window.innerWidth||0);$(function(){//start slider
function a(){clearInterval(s)}/** animate slides function **/function b(){$(".slide").css({left:"-100%",opacity:"0"}),$(".slide"+q).css({left:"0","z-index":"1",opacity:"0"}).animate({left:"0",opacity:"1"},900)}function c(){o.find(".progress").each(function(a){$(this).css({width:a<q?"100%":"0"})})}function d(){r=0}function e(){d(),b()}function f(){100<=r?(a(),r=0,q=q===p?0:q+1,c(),s=setInterval(f,75),e()):(r++,$(".progress"+q+"").css("background-color","#fff"),$(".progress"+q+"").css("width",r+"%"))}function g(){d(),b(),c()}// advance slider when clicking on it
function h(){$(".imperial, .imperialText").removeClass("active"),$(".metric, .metricText").addClass("active"),$(".metricText").removeClass("hidden"),$(".imperialText").addClass("hidden"),setCookie("gac_units","metric")}function k(){$(".imperial, .imperialText").addClass("active"),$(".metric, .metricText").removeClass("active"),$(".metricText").addClass("hidden"),$(".imperialText").removeClass("hidden"),setCookie("gac_units","imperial")}/** ==========
    * cabin config 
    ========== **/function l(){for(var a=1;6>a;a++)$(".slide"+a+"num").removeClass("active")}/** switch between cabin slides  desktop **/function m(){x.animate({opacity:0},1e3,function(){x.remove()})}$(".threeSixty-view-section__placeholder").on("click",function(){$(this).hide(),$(".threeSixty-view-section__vr").show()}),$(".subnav .scroll_target").on("click",function(){// scrollToJQ args: (selector, added offset, time)
var a=$(this).attr("data-adjust")?parseInt($(this).attr("data-adjust")):0,b=900>viewportWidth?95+a:125+a;scrollToJQ($("#"+$(this).attr("data-target")),b,100)});var n=$(".subnav [data-target]");$(window).on("scroll",function(){var a=$(window).scrollTop(),b=a+$(window).height(),c=a+.95*(b-a);// 25% from top of viewport
n.each(function(){var a=$(this).attr("data-target"),b=$("#"+a).offset().top,d=$("#"+$(this).attr("data-target-end")).offset().top;b<=c&&d>=c-.5*$(window).height()?$(this).addClass("active"):$(this).removeClass("active")})});/** ==========================
     * bar slider JS starts here 
    ========================== **/var o=$(".aircraft__slideshow"),p=$(".bar .holder").length-1,q=0,r=0;(function(){q=0,r=0,o.find(".slide").css({left:"-100%",zIndex:"0"}),o.find(".progress").css({width:"0%"})})();var s=setInterval(f,75);e(),$(".holder, .slide").click(function(){q=$(this).index()===p?0:q+1,g()}),$(".holder").hover(function(){a()}),$(".holder").mouseleave(function(){s=setInterval(f,75)}),$("button.aircraft__slideshow__button svg").click(function(){q=$(this).parents("button").hasClass("next")?q==p?0:q+1:0==q?p:q-1,g()}),$("#accordion .accordionHeader").on("mousedown",function(a){a.preventDefault()}),$("#accordion .accordionHeader").click(function(a){var b=$(a.target).children(),c=$(this).closest(".accordionSection");c.hasClass("active")?($(this).attr("aria-expanded",!1),c.removeClass("active"),$(".accordionBody",c).animate("display","none"),$(".accordion-button > span.open",c).removeClass("hidden"),$(".accordion-button > span.close",c).removeClass("hidden"),$(".accordion-button > span.close",c).addClass("hidden")):($(this).attr("aria-expanded",!0),c.addClass("active"),$(".accordionBody",c).animate("display","block"),$(".accordion-button > span.open",c).removeClass("hidden"),$(".accordion-button > span.close",c).removeClass("hidden"),$(".accordion-button > span.open",c).addClass("hidden"))}),$(".accordionHeader:nth-child(5)").addClass("border-bottom-always"),$(".accordionHeader:last-child").addClass("border-bottom-always"),"metric"==getCookie("gac_units")?h():"imperial"==getCookie("gac_units")&&k(),$(".metric").click(function(a){a.preventDefault(),$(this).hasClass("active")||h()}),$(".imperial").click(function(a){a.preventDefault(),$(this).hasClass("active")||k()});/** ============
    * mobile subnav 
    ============ **/var t=$(".subnav-wrapper-mobile"),u=t.find(".closed"),v=t.find(".opened");u.on("click",function(){$(this).addClass("hidden"),v.removeClass("hidden"),t.addClass("opened")}),v.on("click",function(){$(this).addClass("hidden"),u.removeClass("hidden"),t.removeClass("opened")}),$(".cabinConfig-slider > .flickity-button").click(function(){$(".slide1cabin").hasClass("is-selected")&&(l(),$(".slide1num").addClass("active")),$(".slide2cabin").hasClass("is-selected")&&(l(),$(".slide2num").addClass("active")),$(".slide3cabin").hasClass("is-selected")&&(l(),$(".slide3num").addClass("active")),$(".slide4cabin").hasClass("is-selected")&&(l(),$(".slide4num").addClass("active"))}),$(".cabinConfig-slider-mobile.option-1").addClass("active");//remove active class to other sliders just in case
for(var w=2;5>w;w++)$(".cabinConfig-slider-mobile.option-"+w).addClass("hidden--below");/** slide update based on select option  **/$(".config-selector").change(function(){$(this).find(":selected").addClass("selected").siblings("option").removeClass("selected");var a=$(".config-selector").val(),b=["option-1","option-2","option-3","option-4"];if(-1!=b.indexOf(a)){// get a local copy of the array
var c=b.slice();// remove the selected configuration
c.splice(c.indexOf(a),1),$(".cabinConfig-slider-mobile."+a).removeClass("hidden--below"),$(".cabinConfig-slider-mobile."+a).addClass("active");//remove active class to other sliders just in case and hide other sliders
for(var d=0;d<c.length;d++)$(".cabinConfig-slider-mobile."+c[d]).removeClass("active").addClass("hidden--below");// remove active and hidden
for(var d=1;5>d;d++)$(".select"+d+"num").removeClass("active").removeClass("hidden");// add appropriate active class
$(".select"+a.split("-")[1]+"num").addClass("active");//add appropriate hidden class
for(var d=0;d<c.length;d++)$(".select"+c[d].split("-")[1]+"num").addClass("hidden");// trigger update to comparison overlay data area
$("#cabin_size_form input:checked").trigger("change")}}),$(".cabinConfig-slider").on("change.flickity",function(a,b){for(var c=1;5>c;c++)$(".slide"+c+"num").removeClass("active");$(".slide"+(b+1)+"num").addClass("active")}),$(".compare-checkbox").off("change").on("change",function(){m();var a=$(this),b=$(this).parents(".button_group").index(),c=$(".cabinConfig-slider-mobile"),d=$(".carousel-wrapper.mobile-section").is(":visible");// activate selected image
if($(".compare-checkbox").each(function(){$(this).parents(".button_group").index()!=b&&$(this).prop("checked",!1)}),$(".overlay, .data-overlay, [data-compare='no-compare']").addClass("inactive").removeClass("selected"),$(a).prop("checked")){var e=$(".carousel.mobile-section.active").attr("data-config"),f=d?$(".overlay[data-compare='overlay-"+$(this).val()+"'], .data-overlay[data-compare='overlay-"+$(this).val()+"'][data-config='"+e+"']"):$(".overlay[data-compare='overlay-"+$(this).val()+"'], .data-overlay[data-compare='overlay-"+$(this).val()+"']");f.removeClass("inactive").addClass("selected").css({opacity:0}).animate({opacity:1},200),$(".overlay.inactive, .data-overlay.inactive, [data-compare='no-compare'].inactive").animate({opacity:0},200),d&&c.each(function(){$(this).flickity("next")})}else $("[data-compare='no-compare']").removeClass("inactive").addClass("selected").animate({opacity:1},200),$(".overlay.inactive, .data-overlay.inactive").animate({opacity:0},200),d&&c.each(function(){$(this).flickity("previous")})});// activate swipe prompt in 1.5s
// if it exists and enters viewport
var x=$(".swipe-prompt");x.length&&(x.eq(0).on("click",function(){m()}),x[0].addEventListener("touchstart",function(){m()},!1),$(window).on("scroll.swipeprompt",function(){x.length&&x.viewport()&&($(window).off("scroll.swipeprompt"),setTimeout(function(){x.animate({opacity:.5},500,function(){setTimeout(function(){m()},7e3)})},1500))}),$(window).trigger("scroll"))});