var lang=document.querySelector("html").getAttribute("lang");"zh-Hans"===lang&&(lang="cn");var globalLangData=window._DATA.javascript[lang].contacts,phoneLabels=window._DATA.contacts.phoneLabels;$(document).ready(function(){// check which button clicked to update slider
function a(a){"prev"===a&&(g=f(),prevInd=g,--g,e(g),b(prevInd,g,100)),"next"===a&&(g=f(),prevInd=g,++g,e(g),b(prevInd,g,-100))}// handle transform direction of slides and active slide
function b(a,b,d){c(d),$(".slide-"+b).addClass("active"),$("#bar"+b).addClass("active-bar")}function c(){k.removeClass("active"),j.removeClass("active-bar")}function d(){g=1,j.first().addClass("active-bar"),k.first().addClass("active")}// check if end or beginning of slider
function e(a){a>m&&d(),1>a&&(g=m,$("#bar"+m).addClass("active-bar"),$(".slide-"+m).addClass("active"))}// get the active id or index of the slide
function f(){var a=parseInt($(".active-bar").attr("id").slice(3,5));return a}// carousel variables
var g,h,l,j=$(".bar"),k=$(".special-missions-slide"),m=$(".special-missions-slide").length,n=[],o=$("#sm_contact");//index value of slider
// clicking on a bar icon will jump you to a specific slide
// start slider
// process data returned from the contact feed
$("#next").on("click",function(){a("next")}),$("#prev").on("click",function(){a("prev")}),$(".special-missions-slide").on("touchstart touchend touchmove",function(b){return b.preventDefault(),"touchstart"==b.type?(touchPositionStart=b.touches[0].clientX,touchPositionStart):"touchmove"==b.type?(n.push(b.originalEvent.changedTouches[0].clientX),n):void("touchend"==b.type&&(touchPositionEnd=n.pop(),1<n.length&&(touchPositionDiff=touchPositionEnd-touchPositionStart,40<=touchPositionDiff&&a("prev"),-40>=touchPositionDiff&&a("next"))))}),$(".special-missions-slide").on("mouseclick mousedown mouseup",function(b){return b.preventDefault(),"mousedown"===b.type?(positionStart=b.originalEvent.clientX,positionStart):void("mouseup"===b.type&&(positionEnd=b.originalEvent.clientX,positionDiff=positionStart-positionEnd,40<=positionDiff&&a("next"),-40>=positionDiff&&a("prev")))}),$(".bar").on("click",function(){var a=$(this).data("index");$(".special-missions-slide").each(function(){$(this).removeClass("active")}),$(".bar").each(function(){$(this).removeClass("active-bar")}),$(".special-missions-slide[data-index='"+a+"']").addClass("active"),$(".bar[data-index='"+a+"']").addClass("active-bar")}),d(),$.get("https://assets.gulfstream.aero/data-service/feeds/contacts.json").done(function(a){h=[];for(var b=0;b<a.length;b++)a[b].Division__c&&"government"==a[b].Division__c.toLowerCase()&&(a[b].Title__c&&"regional vice president"==a[b].Title__c.toLowerCase()?l=a[b]:h.push(a[b]));if(h=h.sort(function(c,a){return c.Last_Name__c<a.Last_Name__c?-1:c.Last_Name__c>a.Last_Name__c?1:0}),l&&h.unshift(l),0<h.length)for(var c=0;c<h.length;c++){var d=h[c].First_Name__c+" "+h[c].Last_Name__c,e=h[c].Title__c,f=h[c].Profile_Image__c,g=h[c].Sales_Territory__c,m=h[c].Email__c,n="";if(h[c].phones&&0<h[c].phones.length)for(var p=0;p<h[c].phones.length;p++)""!==h[c].phones[p].label&&(phoneLabel=h[c].phones[p].label,translatedLabel=phoneLabels[phoneLabel][lang],"undefined"==typeof translatedLabel&&(translatedLabel=phoneLabel+": "),n+="<li>"+translatedLabel+"<a href=\"tel:"+h[c].phones[p].number+"\">"+h[c].phones[p].number+"</a></li>");placeholder_html=f?"<div class='sm__contacts--picture'><img src='"+f+"' alt='"+d+"'width='150' height='150'></div>":"","Regional Vice President"===e&&(e=globalLangData.rvp_not_sales),"Military and Special Missions Sales"===g&&(g=globalLangData.msms),o.append("<div class=\"sm__contact-wrapper\">"+placeholder_html+"<div class=\"preowned__contact preowned__contact--sm\"><h1>"+d+"</h1><h2>"+e+"</h2><h3>"+g+"</h3><ul>"+n+"<li><a href=\"mailto:"+m+"?subject=Gulfstream%20Special%20Missions%20Inquiry\">"+m+"</a></li></ul></div></div>")}else o.append(window._DATA.javascript[lang].contacts.no_contacts)}).fail(function(a){console.error("error:",a),o.append(window._DATA.javascript[lang].contacts.no_contacts)})});